cacheFolder: ./.yarn/cache

defaultSemverRangePrefix: ^

enableMessageNames: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-changed.cjs
    spec: "https://github.com/Dcard/yarn-plugins/releases/latest/download/plugin-changed.js"

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.1.1.cjs
